package com.dylar.mobile.mouaugpcalc;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dylar.mobile.mouaugpcalc.Level;
import com.dylar.mobile.mouaugpcalc.Semester;
import com.dylar.mobile.mouaugpcalc.Courses;

import com.dylar.mobile.mouaugpcalc.LevelDao;
import com.dylar.mobile.mouaugpcalc.SemesterDao;
import com.dylar.mobile.mouaugpcalc.CoursesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig levelDaoConfig;
    private final DaoConfig semesterDaoConfig;
    private final DaoConfig coursesDaoConfig;

    private final LevelDao levelDao;
    private final SemesterDao semesterDao;
    private final CoursesDao coursesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        levelDaoConfig = daoConfigMap.get(LevelDao.class).clone();
        levelDaoConfig.initIdentityScope(type);

        semesterDaoConfig = daoConfigMap.get(SemesterDao.class).clone();
        semesterDaoConfig.initIdentityScope(type);

        coursesDaoConfig = daoConfigMap.get(CoursesDao.class).clone();
        coursesDaoConfig.initIdentityScope(type);

        levelDao = new LevelDao(levelDaoConfig, this);
        semesterDao = new SemesterDao(semesterDaoConfig, this);
        coursesDao = new CoursesDao(coursesDaoConfig, this);

        registerDao(Level.class, levelDao);
        registerDao(Semester.class, semesterDao);
        registerDao(Courses.class, coursesDao);
    }
    
    public void clear() {
        levelDaoConfig.clearIdentityScope();
        semesterDaoConfig.clearIdentityScope();
        coursesDaoConfig.clearIdentityScope();
    }

    public LevelDao getLevelDao() {
        return levelDao;
    }

    public SemesterDao getSemesterDao() {
        return semesterDao;
    }

    public CoursesDao getCoursesDao() {
        return coursesDao;
    }

}
